services:
  stats-db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - stats-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ewm-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-db:
    image: postgres:16.1
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: user-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

volumes:
  ewm-db-data:
  stats-db-data:
  user-db-data: