server:
  port: 0

grpc:
  server:
    port: 0

spring:
  application:
    name: collector

collector:
  kafka:
    producer:
      properties:
        "bootstrap.servers": localhost:9092
        "client.id": "stats.collector"
        "key.serializer": org.apache.kafka.common.serialization.StringSerializer
        "value.serializer": ru.practicum.kafka.AvroSerializer
      topic: stats.user-actions.v1

logging:
  level:
    ru:
      practicum: TRACE
    org:
      springframework: ERROR
      apache.kafka: ERROR