spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
           enabled: true
      routes:
        - id: main-service
          uri: lb://main-service
          predicates:
            - Path=/categories/**, /admin/**, /users/**, /events/**, /compilations/**

        - id: stats-server
          uri: lb://stats-server
          predicates:
            - Path=/hit/**, /stats/**

server:
  port: 8080