server:
  port: 0

grpc:
  client:
    analyzer: # <- должно соответствовать значению в @GrpcClient
      address: 'discovery:///analyzer' # адрес gRPC-сервиса
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    collector: # <- должно соответствовать значению в @GrpcClient
      address: 'discovery:///collector' # адрес gRPC-сервиса
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  application:
    name: event-service

  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/event-db
    username: postgres
    password: '12345'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG